version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: rafaelnec/jenkins:latest
    container_name: jenkins
    restart: unless-stopped
    user: jenkins
    volumes:
      - .:/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/jenkins_home"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"